project_id = "psvhphxrhunptbramxoq"

[functions.roll_dice]
verify_jwt = false

[functions.submit_mcq]
verify_jwt = false

[functions.buy_tile]
verify_jwt = false

[functions.build_layer]
verify_jwt = false

[functions.end_turn]
verify_jwt = false

[functions.start_game]
verify_jwt = false
