/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModeSelectRouteImport } from './routes/mode-select'
import { Route as IndexRouteImport } from './routes/index'

const ModeSelectRoute = ModeSelectRouteImport.update({
  id: '/mode-select',
  path: '/mode-select',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mode-select': typeof ModeSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mode-select': typeof ModeSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mode-select': typeof ModeSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mode-select'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mode-select'
  id: '__root__' | '/' | '/mode-select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModeSelectRoute: typeof ModeSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mode-select': {
      id: '/mode-select'
      path: '/mode-select'
      fullPath: '/mode-select'
      preLoaderRoute: typeof ModeSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModeSelectRoute: ModeSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
